import type { City, HourForecast, Place, Sky } from "./types";

function forecast(pattern: Array<[Sky, number]>): HourForecast[] {
  return pattern.map(([sky, tempC], i) => ({ hour: 8 + i, sky, tempC }));
}

export const CITIES: City[] = [
  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    center: { lat: 52.5155, lng: 13.3902 },
    summary: "Museums, canals and very large parks.",
    forecast: forecast([
      ["cloud", 14],
      ["sun", 16],
      ["sun", 18],
      ["sun", 20],
      ["cloud", 21],
      ["cloud", 21],
      ["rain", 19],
      ["rain", 18],
      ["rain", 17],
      ["cloud", 16],
      ["cloud", 15],
      ["cloud", 14],
      ["cloud", 13],
    ]),
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    center: { lat: 48.8606, lng: 2.3376 },
    summary: "Galleries, gardens and riverside walks.",
    forecast: forecast([
      ["sun", 15],
      ["sun", 17],
      ["sun", 19],
      ["sun", 21],
      ["sun", 22],
      ["cloud", 22],
      ["cloud", 21],
      ["cloud", 20],
      ["rain", 18],
      ["rain", 17],
      ["cloud", 16],
      ["cloud", 15],
      ["cloud", 15],
    ]),
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    center: { lat: 38.7139, lng: -9.1394 },
    summary: "Hill viewpoints, tiles and tram lines.",
    
    forecast: forecast([
      ["cloud", 17],
      ["sun", 19],
      ["sun", 22],
      ["sun", 24],
      ["sun", 26],
      ["sun", 27],
      ["sun", 27],
      ["sun", 26],
      ["cloud", 24],
      ["cloud", 23],
      ["cloud", 21],
      ["cloud", 20],
      ["cloud", 19],
    ]),
  } as City,
];

const h = (openH: number, closeH: number) => ({ open: openH * 60, close: closeH * 60 });

export const PLACES: Place[] = [
  // ---------------- Berlin ----------------
  {
    id: "b-pergamon",
    cityId: "berlin",
    name: "Pergamon Museum",
    category: "art",
    tags: ["art", "history", "indoor", "museum"],
    lat: 52.5212,
    lng: 13.3969,
    priceEur: 14,
    durationMin: 90,
    outdoor: false,
    hours: h(10, 18),
    blurb: "Antiquities and monumental architecture on Museum Island.",
  },
  {
    id: "b-altenationalgalerie",
    cityId: "berlin",
    name: "Alte Nationalgalerie",
    category: "art",
    tags: ["art", "painting", "indoor"],
    lat: 52.5208,
    lng: 13.398,
    priceEur: 12,
    durationMin: 75,
    outdoor: false,
    hours: h(10, 18),
    blurb: "19th-century painting and sculpture.",
  },
  {
    id: "b-hamburger",
    cityId: "berlin",
    name: "Hamburger Bahnhof",
    category: "art",
    tags: ["art", "contemporary", "indoor"],
    lat: 52.5288,
    lng: 13.3719,
    priceEur: 10,
    durationMin: 80,
    outdoor: false,
    hours: h(10, 18),
    blurb: "Contemporary art in a converted railway station.",
  },
  {
    id: "b-eastside",
    cityId: "berlin",
    name: "East Side Gallery",
    category: "art",
    tags: ["art", "street art", "history", "outdoor", "free"],
    lat: 52.505,
    lng: 13.4396,
    priceEur: 0,
    durationMin: 45,
    outdoor: true,
    hours: null,
    blurb: "Painted stretch of the Berlin Wall along the Spree.",
  },
  {
    id: "b-tiergarten",
    cityId: "berlin",
    name: "Tiergarten",
    category: "park",
    tags: ["park", "nature", "outdoor", "free", "walk"],
    lat: 52.5145,
    lng: 13.3501,
    priceEur: 0,
    durationMin: 50,
    outdoor: true,
    hours: null,
    blurb: "Berlin's huge central park, all paths and ponds.",
  },
  {
    id: "b-mauerpark",
    cityId: "berlin",
    name: "Mauerpark",
    category: "park",
    tags: ["park", "music", "market", "outdoor", "free"],
    lat: 52.5416,
    lng: 13.4021,
    priceEur: 0,
    durationMin: 60,
    outdoor: true,
    hours: null,
    blurb: "Flea market, karaoke and a slope full of people.",
  },
  {
    id: "b-tempelhof",
    cityId: "berlin",
    name: "Tempelhofer Feld",
    category: "park",
    tags: ["park", "outdoor", "free", "unusual"],
    lat: 52.4757,
    lng: 13.4032,
    priceEur: 0,
    durationMin: 60,
    outdoor: true,
    hours: h(7, 21),
    blurb: "A former airport turned into an enormous open field.",
  },
  {
    id: "b-markthalle",
    cityId: "berlin",
    name: "Markthalle Neun",
    category: "food",
    tags: ["food", "market", "indoor", "lunch"],
    lat: 52.5021,
    lng: 13.4318,
    priceEur: 14,
    durationMin: 50,
    outdoor: false,
    hours: h(10, 18),
    blurb: "Covered market hall with food stalls.",
  },
  {
    id: "b-mustafas",
    cityId: "berlin",
    name: "Mehringdamm Street Food",
    category: "food",
    tags: ["food", "cheap", "lunch", "outdoor"],
    lat: 52.4935,
    lng: 13.3875,
    priceEur: 8,
    durationMin: 30,
    outdoor: true,
    hours: h(11, 22),
    blurb: "Famous kerbside queue, quick and cheap.",
  },
  {
    id: "b-cafe-kranzler",
    cityId: "berlin",
    name: "Café am Neuen See",
    category: "food",
    tags: ["food", "coffee", "park", "rest"],
    lat: 52.5085,
    lng: 13.3434,
    priceEur: 9,
    durationMin: 40,
    outdoor: true,
    hours: h(10, 21),
    blurb: "Lakeside beer garden inside the Tiergarten.",
  },
  {
    id: "b-brandenburg",
    cityId: "berlin",
    name: "Brandenburg Gate",
    category: "history",
    tags: ["history", "landmark", "outdoor", "free"],
    lat: 52.5163,
    lng: 13.3777,
    priceEur: 0,
    durationMin: 25,
    outdoor: true,
    hours: null,
    blurb: "The city's best known landmark.",
  },
  {
    id: "b-memorial",
    cityId: "berlin",
    name: "Memorial to the Murdered Jews of Europe",
    category: "history",
    tags: ["history", "memorial", "outdoor", "free"],
    lat: 52.5139,
    lng: 13.3789,
    priceEur: 0,
    durationMin: 30,
    outdoor: true,
    hours: null,
    blurb: "2,711 concrete slabs on a sloping field.",
  },
  {
    id: "b-fernsehturm",
    cityId: "berlin",
    name: "TV Tower viewing deck",
    category: "view",
    tags: ["view", "indoor", "landmark"],
    lat: 52.5208,
    lng: 13.4094,
    priceEur: 25,
    durationMin: 45,
    outdoor: false,
    hours: h(9, 23),
    blurb: "The whole city from 200 metres up.",
  },
  {
    id: "b-klunkerkranich",
    cityId: "berlin",
    name: "Klunkerkranich rooftop",
    category: "view",
    tags: ["view", "music", "outdoor", "sunset"],
    lat: 52.4814,
    lng: 13.4353,
    priceEur: 5,
    durationMin: 50,
    outdoor: true,
    hours: h(15, 23),
    blurb: "Rooftop garden bar above a car park.",
  },

  // ---------------- Paris ----------------
  {
    id: "p-orsay",
    cityId: "paris",
    name: "Musée d'Orsay",
    category: "art",
    tags: ["art", "painting", "indoor", "museum"],
    lat: 48.86,
    lng: 2.3266,
    priceEur: 16,
    durationMin: 100,
    outdoor: false,
    hours: h(9, 18),
    blurb: "Impressionists in a former railway station.",
  },
  {
    id: "p-orangerie",
    cityId: "paris",
    name: "Musée de l'Orangerie",
    category: "art",
    tags: ["art", "indoor", "museum", "quiet"],
    lat: 48.8638,
    lng: 2.3226,
    priceEur: 12,
    durationMin: 60,
    outdoor: false,
    hours: h(9, 18),
    blurb: "Monet's water lilies in two oval rooms.",
  },
  {
    id: "p-pompidou",
    cityId: "paris",
    name: "Centre Pompidou",
    category: "art",
    tags: ["art", "contemporary", "indoor"],
    lat: 48.8607,
    lng: 2.3522,
    priceEur: 15,
    durationMin: 90,
    outdoor: false,
    hours: h(11, 21),
    blurb: "Modern art behind coloured pipework.",
  },
  {
    id: "p-louvre",
    cityId: "paris",
    name: "Louvre",
    category: "art",
    tags: ["art", "history", "indoor", "museum"],
    lat: 48.8606,
    lng: 2.3376,
    priceEur: 22,
    durationMin: 120,
    outdoor: false,
    hours: h(9, 18),
    blurb: "Enormous. Pick two wings and accept defeat.",
  },
  {
    id: "p-tuileries",
    cityId: "paris",
    name: "Jardin des Tuileries",
    category: "park",
    tags: ["park", "outdoor", "free", "walk"],
    lat: 48.8635,
    lng: 2.3275,
    priceEur: 0,
    durationMin: 45,
    outdoor: true,
    hours: h(7, 21),
    blurb: "Gravel avenues between the Louvre and Concorde.",
  },
  {
    id: "p-luxembourg",
    cityId: "paris",
    name: "Jardin du Luxembourg",
    category: "park",
    tags: ["park", "outdoor", "free", "rest"],
    lat: 48.8462,
    lng: 2.3372,
    priceEur: 0,
    durationMin: 50,
    outdoor: true,
    hours: h(8, 20),
    blurb: "Green chairs around a pond, the classic Paris sit-down.",
  },
  {
    id: "p-buttes",
    cityId: "paris",
    name: "Buttes-Chaumont",
    category: "park",
    tags: ["park", "outdoor", "free", "view"],
    lat: 48.8799,
    lng: 2.3822,
    priceEur: 0,
    durationMin: 60,
    outdoor: true,
    hours: h(7, 22),
    blurb: "Cliffs, a temple and a suspension bridge.",
  },
  {
    id: "p-marais-falafel",
    cityId: "paris",
    name: "Rue des Rosiers falafel",
    category: "food",
    tags: ["food", "cheap", "lunch"],
    lat: 48.8573,
    lng: 2.3595,
    priceEur: 9,
    durationMin: 30,
    outdoor: true,
    hours: h(11, 19),
    blurb: "Queue, paper wrap, eat standing up.",
  },
  {
    id: "p-marche",
    cityId: "paris",
    name: "Marché des Enfants Rouges",
    category: "market",
    tags: ["market", "food", "lunch"],
    lat: 48.8631,
    lng: 2.3627,
    priceEur: 15,
    durationMin: 50,
    outdoor: false,
    hours: h(9, 19),
    blurb: "The city's oldest covered market.",
  },
  {
    id: "p-cafe-flore",
    cityId: "paris",
    name: "Café de Flore",
    category: "food",
    tags: ["food", "coffee", "rest"],
    lat: 48.8542,
    lng: 2.3327,
    priceEur: 12,
    durationMin: 40,
    outdoor: true,
    hours: h(8, 23),
    blurb: "Expensive coffee, excellent people-watching.",
  },
  {
    id: "p-notredame",
    cityId: "paris",
    name: "Notre-Dame & Île de la Cité",
    category: "history",
    tags: ["history", "landmark", "outdoor", "free"],
    lat: 48.853,
    lng: 2.3499,
    priceEur: 0,
    durationMin: 40,
    outdoor: true,
    hours: null,
    blurb: "The cathedral and the island around it.",
  },
  {
    id: "p-sainte-chapelle",
    cityId: "paris",
    name: "Sainte-Chapelle",
    category: "history",
    tags: ["history", "indoor", "art"],
    lat: 48.8554,
    lng: 2.345,
    priceEur: 13,
    durationMin: 45,
    outdoor: false,
    hours: h(9, 17),
    blurb: "Fifteen windows of stained glass, floor to ceiling.",
  },
  {
    id: "p-montmartre",
    cityId: "paris",
    name: "Montmartre & Sacré-Cœur steps",
    category: "view",
    tags: ["view", "outdoor", "free", "walk"],
    lat: 48.8867,
    lng: 2.3431,
    priceEur: 0,
    durationMin: 60,
    outdoor: true,
    hours: null,
    blurb: "Uphill, but the whole city opens up.",
  },
  {
    id: "p-seine",
    cityId: "paris",
    name: "Seine quayside walk",
    category: "view",
    tags: ["view", "walk", "outdoor", "free"],
    lat: 48.8566,
    lng: 2.3402,
    priceEur: 0,
    durationMin: 35,
    outdoor: true,
    hours: null,
    blurb: "Down at water level, away from traffic.",
  },

  // ---------------- Lisbon ----------------
  {
    id: "l-gulbenkian",
    cityId: "lisbon",
    name: "Gulbenkian Museum",
    category: "art",
    tags: ["art", "indoor", "museum", "park"],
    lat: 38.7376,
    lng: -9.1538,
    priceEur: 10,
    durationMin: 90,
    outdoor: false,
    hours: h(10, 18),
    blurb: "A superb collection set in its own garden.",
  },
  {
    id: "l-maat",
    cityId: "lisbon",
    name: "MAAT",
    category: "art",
    tags: ["art", "contemporary", "indoor", "river"],
    lat: 38.6957,
    lng: -9.1944,
    priceEur: 11,
    durationMin: 70,
    outdoor: false,
    hours: h(11, 19),
    blurb: "Wave-shaped art museum on the riverbank.",
  },
  {
    id: "l-azulejo",
    cityId: "lisbon",
    name: "National Tile Museum",
    category: "art",
    tags: ["art", "history", "indoor"],
    lat: 38.7249,
    lng: -9.1136,
    priceEur: 8,
    durationMin: 70,
    outdoor: false,
    hours: h(10, 18),
    blurb: "Five centuries of azulejos in a convent.",
  },
  {
    id: "l-berardo",
    cityId: "lisbon",
    name: "Berardo Collection",
    category: "art",
    tags: ["art", "modern", "indoor"],
    lat: 38.6957,
    lng: -9.2075,
    priceEur: 5,
    durationMin: 70,
    outdoor: false,
    hours: h(10, 19),
    blurb: "Modern and contemporary art in Belém.",
  },
  {
    id: "l-estrela",
    cityId: "lisbon",
    name: "Jardim da Estrela",
    category: "park",
    tags: ["park", "outdoor", "free", "rest"],
    lat: 38.7139,
    lng: -9.1606,
    priceEur: 0,
    durationMin: 45,
    outdoor: true,
    hours: h(7, 22),
    blurb: "Shaded paths, a bandstand and a duck pond.",
  },
  {
    id: "l-estufa",
    cityId: "lisbon",
    name: "Estufa Fria greenhouse",
    category: "park",
    tags: ["park", "indoor", "nature", "quiet"],
    lat: 38.7276,
    lng: -9.1531,
    priceEur: 3,
    durationMin: 50,
    outdoor: false,
    hours: h(10, 18),
    blurb: "A cool, planted glasshouse — good in rain.",
  },
  {
    id: "l-principereal",
    cityId: "lisbon",
    name: "Príncipe Real garden",
    category: "park",
    tags: ["park", "outdoor", "free", "shopping"],
    lat: 38.7159,
    lng: -9.1497,
    priceEur: 0,
    durationMin: 35,
    outdoor: true,
    hours: null,
    blurb: "One enormous cedar and a ring of benches.",
  },
  {
    id: "l-timeout",
    cityId: "lisbon",
    name: "Time Out Market",
    category: "market",
    tags: ["market", "food", "indoor", "lunch"],
    lat: 38.7067,
    lng: -9.1459,
    priceEur: 16,
    durationMin: 55,
    outdoor: false,
    hours: h(10, 23),
    blurb: "Dozens of kitchens under one roof.",
  },
  {
    id: "l-pasteis",
    cityId: "lisbon",
    name: "Pastéis de Belém",
    category: "food",
    tags: ["food", "cheap", "rest", "coffee"],
    lat: 38.6975,
    lng: -9.2033,
    priceEur: 6,
    durationMin: 30,
    outdoor: false,
    hours: h(8, 20),
    blurb: "The custard tarts, still warm.",
  },
  {
    id: "l-tasca",
    cityId: "lisbon",
    name: "Bairro Alto tasca lunch",
    category: "food",
    tags: ["food", "lunch", "cheap"],
    lat: 38.7131,
    lng: -9.1449,
    priceEur: 12,
    durationMin: 45,
    outdoor: false,
    hours: h(12, 23),
    blurb: "Small tiled room, grilled fish, paper tablecloth.",
  },
  {
    id: "l-jeronimos",
    cityId: "lisbon",
    name: "Jerónimos Monastery",
    category: "history",
    tags: ["history", "indoor", "landmark"],
    lat: 38.6979,
    lng: -9.2065,
    priceEur: 10,
    durationMin: 70,
    outdoor: false,
    hours: h(10, 17),
    blurb: "Carved stone cloisters, endlessly detailed.",
  },
  {
    id: "l-castelo",
    cityId: "lisbon",
    name: "São Jorge Castle",
    category: "history",
    tags: ["history", "view", "outdoor"],
    lat: 38.7139,
    lng: -9.1335,
    priceEur: 15,
    durationMin: 75,
    outdoor: true,
    hours: h(9, 21),
    blurb: "Ramparts over the whole of the old city.",
  },
  {
    id: "l-graca",
    cityId: "lisbon",
    name: "Miradouro da Graça",
    category: "view",
    tags: ["view", "outdoor", "free", "sunset"],
    lat: 38.7167,
    lng: -9.1308,
    priceEur: 0,
    durationMin: 30,
    outdoor: true,
    hours: null,
    blurb: "Pine trees, a kiosk and the classic rooftop view.",
  },
  {
    id: "l-santajusta",
    cityId: "lisbon",
    name: "Santa Justa Lift",
    category: "view",
    tags: ["view", "landmark", "outdoor"],
    lat: 38.7123,
    lng: -9.1393,
    priceEur: 6,
    durationMin: 25,
    outdoor: true,
    hours: h(8, 21),
    blurb: "Iron lift straight up out of the Baixa.",
  },
];

export function getCity(cityId: string): City | undefined {
  return CITIES.find((c) => c.id === cityId);
}

export function placesForCity(cityId: string): Place[] {
  return PLACES.filter((p) => p.cityId === cityId);
}

export function getPlace(id: string): Place | undefined {
  return PLACES.find((p) => p.id === id);
}
